Feature/#158
wafflestudio/gatgu-server pull request #161
Opened 2021-06-12 13:05 UTC by Noaarhk

#158

2021-06-15 07:58 UTC, shchoi94 commented on gatgu/article/views.py
> +from gatgu.utils import FieldsNotFilled, QueryParamsNOTMATCH, ArticleNotFound, NotPermitted
> FieldsNotFilled, QueryParamsNOTMATCH, ArticleNotFound, NotPermitted


`{error_name}Exception` 으로 naming하는거 어떤가요? ex) `FieldsNotFilledException`
시리얼라이저에 항상 `{serializer_name}Serializer` 써주듯이

2021-06-15 08:00 UTC, shchoi94 commented on gatgu/article/views.py
> +
이 부분은 지난 번에 함께 이야기 나눈것처럼, 뷰셋 전체에서 전역적으로 쓰기보다는 상황에 맞게 커스텀이 필요한 부분이라
전역으로 선언하면, 이걸 쓰면 되는가 보다 하고 오해를 할수 있기에, 선언 위치를 되돌리면 좋지 않나하는 생각입니다.

2021-06-15 08:02 UTC, shchoi94 commented on gatgu/chat/views.py
> +            #         sum=Sum('wish_price')).values('sum'), output_field=IntegerField()), 0)
전반적으로 코드 설명을 위한 주석이 아닌 주석은 제거해주시면 좋을 것 같습니다.

2021-06-15 08:04 UTC, shchoi94 commented on gatgu/gatgu/utils.py
> +class QueryParamsNOTMATCH(APIException):
`QueryParamsNOTMATCH` -> `QueryParmasIsWrongException`

카멜케이스가 중간에 이상해융

2021-06-15 08:04 UTC, shchoi94 requested changes
리뷰1

2021-06-17 06:36 UTC, Noaarhk commented on gatgu/article/views.py
> +from gatgu.utils import FieldsNotFilled, QueryParamsNOTMATCH, ArticleNotFound, NotPermitted
approve

2021-06-17 06:43 UTC, Noaarhk commented on gatgu/article/views.py
> +
현재 create, list, retrieve 세가지 view에서 전역적으로 사용되고 있어서 전역변수로서 역할을 잘 하고 있는것 같긴 한데, 작업중이지 않은 다른사람이 봤을 때 오해할 수 있다는 의견엔 동의합니다어떻게 하면 좋을 지 조언 부탁드림다

2021-06-19 07:48 UTC, closed without merging